# Generated by Django 5.2.12 on 2026-03-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='userdepartment',
            old_name='department_name',
            new_name='department',
        ),
    ]
